name: CI

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Test
        run: yarn test

